// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Products API",
    "version": "1"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "getProducts",
        "description": "",
        "operationId": "getProducts.get.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Get products success",
            "schema": {
              "$ref": "#/definitions/CreteProductResponse"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/message"
            }
          }
        },
        "security": [
          {
            "Access-Control-Allow-Origin": []
          }
        ]
      },
      "post": {
        "summary": "createProduct",
        "description": "",
        "operationId": "createProduct.post.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "201": {
            "description": "Product was created",
            "schema": {
              "$ref": "#/definitions/CreteProductResponse"
            }
          },
          "404": {
            "description": "Products not found",
            "schema": {
              "$ref": "#/definitions/message"
            }
          }
        },
        "security": [
          {
            "Access-Control-Allow-Origin": []
          }
        ]
      }
    },
    "/products/{productId}": {
      "get": {
        "summary": "getProductById",
        "description": "",
        "operationId": "getProductById.get.products/{productId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "productId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Get product success",
            "schema": {
              "$ref": "#/definitions/ProductInterface"
            }
          },
          "404": {
            "description": "Product not found",
            "schema": {
              "$ref": "#/definitions/message"
            }
          }
        },
        "security": [
          {
            "Access-Control-Allow-Origin": []
          }
        ]
      }
    },
    "/populate": {
      "get": {
        "summary": "populateDataBase",
        "description": "",
        "operationId": "populateDataBase.get.populate",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        },
        "security": [
          {
            "Access-Control-Allow-Origin": []
          }
        ]
      }
    }
  },
  "definitions": {
    "ResponseInterface": {
      "properties": {
        "products": {
          "items": {
            "$ref": "#/definitions/ProductInterface"
          },
          "title": "ResponseInterface.products",
          "type": "array"
        }
      },
      "required": [
        "products"
      ],
      "additionalProperties": false,
      "title": "ResponseInterface",
      "type": "object"
    },
    "ProductInterface": {
      "properties": {
        "count": {
          "title": "ProductInterface.count",
          "type": "number"
        },
        "description": {
          "title": "ProductInterface.description",
          "type": "string"
        },
        "id": {
          "title": "ProductInterface.id",
          "type": "string"
        },
        "price": {
          "title": "ProductInterface.price",
          "type": "number"
        },
        "title": {
          "title": "ProductInterface.title",
          "type": "string"
        }
      },
      "required": [
        "count",
        "description",
        "id",
        "price",
        "title"
      ],
      "additionalProperties": false,
      "title": "ProductInterface",
      "type": "object"
    },
    "StockInterface": {
      "properties": {
        "product_id": {
          "title": "StockInterface.product_id",
          "type": "string"
        },
        "count": {
          "title": "StockInterface.count",
          "type": "number"
        }
      },
      "required": [
        "product_id",
        "count"
      ],
      "additionalProperties": false,
      "title": "StockInterface",
      "type": "object"
    },
    "RequestInterface": {
      "properties": {
        "body": {
          "$ref": "#/definitions/ProductInterface",
          "title": "RequestInterface.body"
        }
      },
      "required": [
        "body"
      ],
      "additionalProperties": false,
      "title": "RequestInterface",
      "type": "object"
    },
    "CreteProductResponse": {
      "allOf": [
        {
          "$ref": "#/definitions/ProductInterface"
        },
        {
          "$ref": "#/definitions/StockInterface"
        }
      ],
      "title": "CreteProductResponse"
    }
  },
  "securityDefinitions": {
    "Access-Control-Allow-Origin": {
      "type": "apiKey",
      "name": "Access-Control-Allow-Origin",
      "in": "header"
    }
  },
  "basePath": "/dev",
  "host": "t9dwam4asf.execute-api.eu-west-1.amazonaws.com"
};